# -*- coding: utf-8 -*-
"""Simple Calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j2HKbcohnkoIDtSS2PCIK-b-k891vw9b
"""

# Creating a calculator
num1 = float(input("enter the first number: "))
num2 = float(input("enter the second number: "))
operation = str(input('enter an operation: ')).lower()
# This calculator can only perform the following operations: addition, subtraction, multiplication, division, exponential.

if (operation == 'addition'):
  result = (num1 + num2)
  print ('the result of the operation is ' + str(result))
elif (operation =='subtraction'):
  result = (num1 - num2)
  print ('the result of the operation is ' + str(result))
elif (operation =='division'):
  result = (num1 / num2)
  print ('the result of the operation is ' + str(result))
elif (operation =='multiplication'):
  result = (num1 * num2)
  print ('the result of the operation is' + str(result))
elif (operation =='exponential'):
  result =(num1 ** num2)
  print ('the result of the operation is' + str(result))
else:
  print('Kindly go and read the instructions')